### ISSUE TITLE
next-typescript@1 with TS numeric separators

### ISSUE THREAD

**Issue by Hurtak** [vercel/next-plugins#194]
Hi, 

recently I updated next-typescript in some smallish example app

```diff
-    "@zeit/next-typescript": "0.1.1",
+    "@zeit/next-typescript": "1.0.1",
```

And everything seems to work fine (tsx, compiling, typechecking) except for numeric separators, which should be TS feature since 2.7 (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html)

```jsx
Error in ./pages/i18n.tsx
Module build failed: SyntaxError: /Users/hurtak/hello/dev/next-stack/pages/i18n.tsx: Identifier directly after number (94:20)

  92 |           {/* https://github.com/yahoo/react-intl/wiki/Components#formattednumber */}
  93 |           <FormattedNumber
> 94 |             value={1_000_000.12456}
     |                     ^
  95 |             style="currency"
  96 |             currency="CZK"
  97 |             currencyDisplay="symbol"
    at _class.raise (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:778:15)
    at _class.readNumber (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:1628:12)
    at _class.getTokenFromCode (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:1395:14)
    at _class.readToken (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:984:12)
    at _class.readToken (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:8118:46)
    at _class.readToken (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:8118:46)
    at _class.readToken (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:8118:46)
    at _class.readToken (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:9904:48)
    at _class.nextToken (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:976:12)
    at _class.next (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:912:10)
    at _class.jsxParseExpressionContainer (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:7945:12)
    at _class.jsxParseAttributeValue (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:7912:23)
    at _class.jsxParseAttribute (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:7968:46)
    at _class.jsxParseOpeningElementAt (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:7984:35)
    at _class.jsxParseElementAt (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:8008:33)
    at _class.jsxParseElementAt (/Users/hurtak/hello/dev/next-stack/node_modules/babylon/lib/index.js:8024:34)
```

Other relevant dependenceis
```
    "next": "6.0.3",
    "typescript": "2.9.1",
```

.babelrc
```json
{
  "env": {
    "development": {
      "presets": [
        "next/babel",
        "@zeit/next-typescript/babel"
      ]
    },
    "production": {
      "presets": [
        "next/babel",
        "@zeit/next-typescript/babel"
      ]
    },
    "test": {
      "presets": [
        [
          "next/babel",
          {
            "preset-env": {
              "modules": "commonjs"
            }
          },
          "@zeit/next-typescript/babel"
        ]
      ]
    }
  }
}
```
(same behaviour with recommended .babelrc)

```json
{
  "presets": [
    "next/babel",
    "@zeit/next-typescript/babel"
  ]
}
```

Probably some upstream issue, but I am not sure where to report.

**Comment by genox** [comment]
I can't get decorators (or transform-class-properties) to work with 1.0.1 of next-typescript either. I think it may be too early to rely on babel (current canary release offers @babel/core@7.0.0-beta.42 - it's beta, so..) for TS transpilation? For now I will stick with 0.1.1.
