### ISSUE TITLE
next-css@^0.2.1-canary.1 + PostCSS fails when postcssLoaderOptions is not set

### ISSUE THREAD

**Issue by ESWAT** [vercel/next-plugins#239]
After finally getting #235 sorted I ran into another issue [occurring here](https://github.com/zeit/next-plugins/blob/canary/packages/next-css/css-loader-config.js#L58)

```
TypeError: Cannot read property 'config' of undefined
    at module.exports (/Users/eswat/app/node_modules/@zeit/next-css/css-loader-config.js:58:28)
    at Object.webpack (/Users/eswat/app/node_modules/@zeit/next-css/index.js:15:36)
    at _callee3$ (/Users/eswat/app/node_modules/next/dist/build/webpack.js:297:38)
    at tryCatch (/Users/eswat/app/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/eswat/app/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/eswat/app/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/eswat/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/eswat/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
    at <anonymous>
```

In my case I did not pass a `postcssLoaderOptions` in my `next.config.js` originally, but adding that key and an empty object fixed the issue. That should probably be optional.

**Comment by damianfrizzi** [comment]
Was running into the same issue. There should probably [be a check here](https://github.com/zeit/next-plugins/blob/canary/packages/next-css/css-loader-config.js#L58) if a postcss config was provided.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
