### ISSUE TITLE
react-slideshow-image not working

### ISSUE THREAD

**Issue by mdsEu** [vercel/next-plugins#356]
Hi, I'm try add react-slideshow-image in my project the next but when compile I get out this error:

react-slideshow-image/lib/components/slideshow/slide.css:1
(function (exports, require, module, __filename, __dirname) { .react-slideshow-wrapper.slide {
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/vaova-front/vaova-next/node_modules/react-slideshow-image/lib/components/slideshow/slide.js:23:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

My next.config.js file are this:
const withSass = require('@zeit/next-sass');
const withCSS = require('@zeit/next-css')

```
module.exports = withCSS(withSass({
  cssModules: true,
  sassLoaderOptions: {
    includePaths: ["assets/styles/sass/*"]
  },
  webpack(config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use:{
        loader: "url-loader",
        options: {
            limit: 100000,
            name: '[name].[ext]'
          }
        }
    });
    return config;
  }
}));
```

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
