### ISSUE TITLE
Sass loader import NPM modules

### ISSUE THREAD

**Issue by stefanfransen** [vercel/next-plugins#379]
I'm trying to import [bootstrap-sass](https://github.com/twbs/bootstrap-sass) inside my sass file using `@zeit/next-sass`.

I'm using the following import:
```@import bootstrap/variables```

I tried putting a `@` before bootstrap with no luck.

I get the following error:
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import bootstrap/variables
^
      File to import not found or unreadable: bootstrap/variables.
      in /Users/stefanfransen/Documents/Development/Node/foj/assets/sass/main.sass (line 92, column 1)
    at runLoaders (/Users/stefanfransen/Documents/Development/Node/foj/node_modules/webpack/lib/NormalModule.js:286:20)
    at /Users/stefanfransen/Documents/Development/Node/foj/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/stefanfransen/Documents/Development/Node/foj/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/stefanfransen/Documents/Development/Node/foj/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/stefanfransen/Documents/Development/Node/foj/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/Users/stefanfransen/Documents/Development/Node/foj/node_modules/async/dist/async.js:2271:31)
    at Object.callback (/Users/stefanfransen/Documents/Development/Node/foj/node_modules/async/dist/async.js:969:16)
    at options.error (/Users/stefanfransen/Documents/Development/Node/foj/node_modules/node-sass/lib/index.js:294:32)

 @ ./pages/_app.js 35:0-34
 @ multi ./pages/_app.js
```

I'm not sure what my mistake is, can anyone point me into the right direction?

Thanks in advance.

Stefan Fransen.

**Comment by selique** [comment]
i have same error!

**Comment by soufDev** [comment]
same error with Semantic UI

**Comment by malixsys** [comment]
did you try `@import ~bootstrap/variables`?

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
