### ISSUE TITLE
withSASS: custom webpack giving window not defined error.

### ISSUE THREAD

**Issue by vikasdomakunti** [vercel/next-plugins#508]
I have my next.config.js as below.

```
\\next.config.js
const withCSS = require('@zeit/next-css');
const withSASS = require('@zeit/next-sass');
const withPlugins = require('next-compose-plugins');
const optimizedImages = require('next-optimized-images');
const path = require("path");

module.exports = withPlugins([
  [withCSS, {
    webpack: function (config) {
      config.module.rules.push({
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 100000,
            name: '[name].[ext]'
          }
        }
      })
      return config
    }
  }],
  [withSASS, {
    webpack: (config) => {
      config.module.rules[3].use = [
        { loader: "style-loader" },
        { loader: "css-loader" },
        { loader: "sass-loader" },
        {
          loader: "sass-resources-loader",
          options: { resources: require(path.join(__dirname, "./cssUtil.js")) }
        }];
      return config;
    }
  }],
  [optimizedImages, {
    optimizeImagesInDev: true
  }]
], (config) => {
  console.log(config);
});
```

Footer.js

```
...
import "Footer.scss";
...
```

Footer.scss

```
.footer {
  ...
}
```

Error

```
 ReferenceError: window is not defined
    at /Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:2240:2
    at /Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:2229:46
    at module.exports../node_modules/style-loader/lib/addStyles.js.module.exports (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:2297:88)
    at Object../src/common/components/Footer/Footer.scss (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:3194:143)
    at __webpack_require__ (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:23:31)
    at Module../src/common/components/Footer/Footer.js (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:3060:71)
    at __webpack_require__ (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:23:31)
    at Module../src/common/components/Footer/index.js (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:3596:65)
    at __webpack_require__ (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:23:31)
    at Module../src/containers/Layout/Layout.js (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:6337:83)
    at __webpack_require__ (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:23:31)
    at Module../src/containers/Layout/index.js (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:6449:65)
    at __webpack_require__ (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:23:31)
    at Module../pages/_app.js (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:2747:81)
    at __webpack_require__ (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/vdoma001/IdeaProjects/7-Eleven-React/.next/server/static/development/pages/_app.js:8381:18)
```

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
