### ISSUE TITLE
Next-css and react-multi-carousel, can't import css file

### ISSUE THREAD

**Issue by artversion-devs** [vercel/next-plugins#519]
I am trying to use 'next-css' to import the needed css file from 'react-multi-carousel' 
I am also using styled jsx along with its sass plugin. 

I am presented with an error (below). A little poking around makes me think that there is a loader issue due to the 'react-multi-carousel/lib/styles.css' file containing references to various font files. E.g. `src:url("./revicons.woff") format('woff'),url("./revicons.ttf") format('ttf'),url("./revicons.eot") format('ttf')`

I need help to find a resolution to this. 

I am aware that I could copy this css file into the static folder, and link it with a Head component. However I am hoping to avoid this. 

**index.js**

```
...
import 'react-multi-carousel/lib/styles.css'
...

```

**next.config.js**
```
const withCSS = require('@zeit/next-css')

module.exports = withCSS()
```

**.babelrc**
```
{
    "presets": [
      [
        "next/babel",
        {
          "styled-jsx": {
              "plugins": ["styled-jsx-plugin-sass"]
            }
        }
      ]
    ],
    "plugins": []
  }
```

**Here's the output from my console when I run a dev server:**

````
[ ready ] compiled successfully
[ event ] build page: /
[ wait ]  compiling ...
> Using external babel configuration
> Location: "/Users/will/newgits/mental-motion/.babelrc"
[styled-jsx] Loading plugin from path: /Users/will/newgits/mental-motion/node_modules/styled-jsx-plugin-sass/index.js
[ error ] ./node_modules/react-multi-carousel/lib/styles.css
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'exportOnlyLocals'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
Could not find files for /index in .next/build-manifest.json
Warning: Received `true` for a non-boolean attribute `jsx`.

If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}.
    in style
    in footer
    in Unknown
    in Fragment
    in Layout
    in Fragment
    in Home
    in Container
    in App
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
ModuleBuildError: Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'exportOnlyLocals'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
    at validate (/Users/will/newgits/mental-motion/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/will/newgits/mental-motion/node_modules/css-loader/dist/index.js:34:28)
    at runLoaders (/Users/will/newgits/mental-motion/node_modules/webpack/lib/NormalModule.js:302:20)
    at /Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/will/newgits/mental-motion/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/will/newgits/mental-motion/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/will/newgits/mental-motion/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
    at runLoaders (/Users/will/newgits/mental-motion/node_modules/webpack/lib/NormalModule.js:302:20)
    at /Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/will/newgits/mental-motion/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:113:20
    at compile (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compiler.js:306:11)
    at hooks.afterCompile.callAsync.err (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compiler.js:631:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/will/newgits/mental-motion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/will/newgits/mental-motion/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compiler.js:628:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/will/newgits/mental-motion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/will/newgits/mental-motion/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compilation.js:1325:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/will/newgits/mental-motion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/will/newgits/mental-motion/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compilation.js:1316:32)
ModuleBuildError: Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'exportOnlyLocals'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
    at validate (/Users/will/newgits/mental-motion/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:49:11)
    at Object.loader (/Users/will/newgits/mental-motion/node_modules/css-loader/dist/index.js:34:28)
    at runLoaders (/Users/will/newgits/mental-motion/node_modules/webpack/lib/NormalModule.js:302:20)
    at /Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/will/newgits/mental-motion/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/will/newgits/mental-motion/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/will/newgits/mental-motion/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
    at runLoaders (/Users/will/newgits/mental-motion/node_modules/webpack/lib/NormalModule.js:302:20)
    at /Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/will/newgits/mental-motion/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/will/newgits/mental-motion/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:113:20
    at compile (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compiler.js:306:11)
    at hooks.afterCompile.callAsync.err (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compiler.js:631:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/will/newgits/mental-motion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/will/newgits/mental-motion/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compiler.js:628:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/will/newgits/mental-motion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/will/newgits/mental-motion/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compilation.js:1325:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/will/newgits/mental-motion/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/will/newgits/mental-motion/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/will/newgits/mental-motion/node_modules/webpack/lib/Compilation.js:1316:32)`
```

**Comment by muthuridennis** [comment]
@will-av Try using this as your config in `next-config.js`

```
module.exports = withCSS({
  webpack(config, options) {
    return config;
  },
});
```

**Comment by kozak-iz-kh** [comment]
> @will-av Try using this as your config in `next-config.js`
> 
> ```
> module.exports = withCSS({
>   webpack(config, options) {
>     return config;
>   },
> });
> ```

doesn't work for me :(

**Comment by kozak-iz-kh** [comment]
here is the solution, that works for me
https://github.com/zeit/next-plugins/issues/70#issuecomment-474722343

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
